name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Lint
      run: bun run lint
    
    - name: Test
      run: bun run test:fast
    
    - name: Debug TypeScript Module Resolution
      run: |
        echo "--- Verifying schema imports in source files ---"
        grep -n "from './schema" src/*.ts || echo "No schema imports found"
        echo "--- Checking if schema.d.ts exists ---"
        ls -la src/schema*
        echo "--- TypeScript version ---"
        bun --version
        npx tsc --version
    
    - name: Build
      run: bun run build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/